[package]
name = "AaveOracle"
version = "1.0.0"
upgrade_policy = "compatible"
authors = []

[addresses]
aave_oracle = "_"
# On deployment, these should be overridden with --named-addresses using the addresses
# documented at https://docs.pyth.network/documentation/pythnet-price-feeds/aptos#addresses
# both mainnet and testnet addresses are the same (cf.https://docs.pyth.network/price-feeds/contract-addresses/aptos)
pyth = "_"
deployer = "_"
wormhole = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
# The Pyth package, and the Wormhole package upon which it dependes, specify assorted
# Aptos dependency revisions that conflict with the revisions specified in this and
# other Aave packages, so to build this package for testing, you'll need to clone
# both the Pyth and Wormohole packages and manually update revisions. Note that the
# .gitignore in this directory excludes both packages, so you can easily clone them.
#
# 1. In this directory, run
#
# git clone https://github.com/wormhole-foundation/wormhole.git
# git clone https://github.com/pyth-network/pyth-crosschain.git
#
# 2. Update pyth-crosschain/target_chains/aptos/contract/Move.toml to specify:
#
# AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }
# MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "main" }
# AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "main" }
# AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token/", rev = "main" }
# Wormhole = { local = "../../../../wormhole/aptos/wormhole" }
# Deployer = { local = "../../../../wormhole/aptos/deployer" }
#
# 3. Update wormhole/aptos/wormhole/Move.toml to specify:
#
# AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }
# MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "main" }
# AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "main" }
# AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token/", rev = "main" }
# Deployer = { local = "../deployer/" }
#
# 4. Update wormhole/aptos/deployer/Move.toml to specify:
#
# [dependencies.AptosFramework]
# git = 'https://github.com/aptos-labs/aptos-core.git'
# rev = 'main'
# subdir = 'aptos-move/framework/aptos-framework'
#
# 5. Update the below line to:
#
# Pyth = { local = "pyth-crosschain/target_chains/aptos/contracts" }
#
# 6. Then you should be able to run aptos move test
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/aptos/contracts", rev = "mainnet" }
AaveConfig = { local = "../aave-config" }
AaveAcl = { local = "../aave-acl" }

