packages:
  - aave-test-kit
  - aave-test-suite

overrides:
  trim@<0.0.3: '>=0.0.3'
  postcss@<7.0.36: '>=7.0.36'
  postcss@<8.4.31: '>=8.4.31'
  minimatch@<3.0.5: '>=3.0.5'
  minimist@>=1.0.0 <1.2.6: '>=1.2.6'
  semver@>=6.0.0 <6.3.1: '>=6.3.1'
  cookie@<0.7.0: '>=0.7.0'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  '@eslint/plugin-kit@<0.3.3': '>=0.3.3'
