name: Build Aptos Documentation

on:
  pull_request:
  merge_group:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  GITHUB_ACTIONS: true
  APTOS_NETWORK: local
  MOVE_VERSION: 2.1
  COMPILER_VERSION: 2.0
  ARTIFACTS_LEVEL: all
  DEFAULT_FUND_AMOUNT: 40000000
  DEFAULT_FUNDER_PRIVATE_KEY: ${{ secrets.GH_DEFAULT_FUNDER_PRIVATE_KEY }}

  # aave profiles
  AAVE_ACL_PRIVATE_KEY: ${{ secrets.GH_AAVE_ACL_PRIVATE_KEY }}
  AAVE_CONFIG_PRIVATE_KEY: ${{ secrets.GH_AAVE_CONFIG_PRIVATE_KEY }}
  AAVE_MATH_PRIVATE_KEY: ${{ secrets.GH_AAVE_MATH_PRIVATE_KEY }}
  AAVE_ORACLE_PRIVATE_KEY: ${{ secrets.GH_AAVE_ORACLE_PRIVATE_KEY }}
  AAVE_POOL_PRIVATE_KEY: ${{ secrets.GH_AAVE_POOL_PRIVATE_KEY }}
  AAVE_MOCK_UNDERLYING_TOKENS_PRIVATE_KEY: ${{ secrets.GH_AAVE_MOCK_UNDERLYING_TOKENS_PRIVATE_KEY }}
  AAVE_LARGE_PACKAGES_PRIVATE_KEY: ${{ secrets.GH_AAVE_LARGE_PACKAGES_PRIVATE_KEY }}
  AAVE_DATA_PRIVATE_KEY: ${{ secrets.GH_AAVE_DATA_PRIVATE_KEY }}
  AAVE_DATA_FEEDS_PRIVATE_KEY: ${{ secrets.GH_AAVE_DATA_FEEDS_PRIVATE_KEY }}
  AAVE_PLATFORM_PRIVATE_KEY: ${{ secrets.GH_AAVE_PLATFORM_PRIVATE_KEY }}

jobs:
  build-docs:
    name: Build Aptos Documentation
    runs-on: Larger-Github-Runners
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Aptos CLI
        uses: ./.github/actions/install-aptos-cli
        with:
          version: "6.2.0"
      - name: Run Aptos Create Local Testnet
        run: |
          make local-testnet &
          echo $! > aptos_serve_pid.txt
      - name: Wait for Aptos Local Testnet to be ready
        run: sleep 20
      - name: Set Local Aptos Workspace Config
        run: make set-workspace-config
      - name: Init Local Aptos Workspace Config
        run: make init-workspace-config
      - name: Run Aptos Create Profiles
        run: make init-profiles
      - name: Create Documentation
        run: make doc-all
      - name: Upload generated Markdown files
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-full
          path: my-docs

  build-mkdocs:
    name: Build and Deploy MkDocs Site
    needs: build-docs
    runs-on: Larger-Github-Runners
    timeout-minutes: 60
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download md artifacts
        uses: actions/download-artifact@v4
        with:
          name: mkdocs-full
          path: my-docs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs & Material theme
        run: pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build
        working-directory: my-docs

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: my-docs/site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
